[package]
name = "clock"
version = "0.1.0"
authors = ["Kenny Kerr <kenny.kerr@microsoft.com>"]
edition = "2018"

[dependencies]
windows = { git = "https://github.com/microsoft/windows-rs" }
bindings = { path = "bindings" }
